name: Github Actions Example
on:
  push:
    branches: 
        - feature/git_**
jobs:
  build:
    name: Build for new feature(s)
    runs-on: windows-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm install
    - name: Test project
      run: npm test